name: charcoal_vendor
description: "Charcoal vendor management app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  lottie: ^3.0.0
  flutter_inset_box_shadow: ^1.0.8
  get: ^4.6.6
  cloud_firestore: ^4.9.3 # firebase cloud storage
  firebase_auth: ^4.16.0 # enable authentication from multiple platform fb/gmail/etc..
  firebase_core: ^2.24.2 # Firebase core API
  firebase_storage: ^11.6.0 # to store image file etc
  image_picker: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  flutter_lints: ^3.0.1

flutter_native_splash:
  # color_dark: "#121212"
  color: "#270E01"
  image: assets/images/fire_splash.png
  android_12: 
    image: assets/images/fire_splash.png
  android: true 

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/charcoal_transparent.png"
  # adaptive_icon_foreground: "#ffffff"
  adaptive_icon_background: "#ffffff" # background theme

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

